version: "3.9"
services:
  web:
    build: .
    depends_on: 
      - redis
    ports: 
      - "${PORT}:${PORT}"
    environment:
      - ENVIRONMENT=${ENV_TYPE}
      - HOST=localhost
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_DB=0
  redis:
    image: redis
    ports:
    - "${REDIS_PORT}:6379"